apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-php-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: php-apache
          image: php-mongo:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          volumeMounts:
            - name: code
              mountPath: /var/www/html
      volumes:
        - name: code
          configMap:
            name: php-code