apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: postgres
        image: registry.redhat.io/rhel8/postgresql-15

        ports:
        - containerPort: 5432

        env:
        - name: POSTGRESQL_USER
          value: postgres
        - name: POSTGRESQL_PASSWORD
          value: postgres
        - name: POSTGRESQL_DATABASE
          value: votes

        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL

        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/pgsql/data

      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
