apiVersion: v1
kind: Service
metadata:
  name: httpd-php-service
  labels:
    app: web
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
    - name: http
      protocol: TCP
      port: 80          # Service port (inside cluster)
      targetPort: 80    # Container port